
INSERT INTO `brands` (`name`) VALUES

('Zoffoli'),
('Millwood Pines'),
('Barewalls');

-- --------------------------------------------------------


INSERT INTO `products` (`name`, `price`, `description`, `category_id`, `brand_id`, `stock`, `image`, `specification`) VALUES
('Giunone Laguna', 2895, 'Our most popular bar globe can store up to 9 glasses and 2 or 3 bottles inside its antique 16th Century southern sphere. Suitable for both large and small spaces, this finely detailed bar globe will add a classic twist to your home. Chestnut-stained solid hardwood legs and a beautifully illustrated lower-base shelf compose the stand. The globe sphere fully rotates around its meridian either when it is open or closed. You can easily move it thanks to its casters.\r\n\r\n- Designed to give a touch of elegance and originality to your living room or study\r\n\r\n- Ideal to accompany an aperitif or an after dinner with friends or work colleagues\r\n\r\n- Perfect for decorating rooms in a classic style but does not exclude more modern locations\r\n\r\n- Suitable for those with small spaces (for greater enhancement of the product we suggest placing it in a space of at least 70 x 70 cm)\r\n\r\nBar accessories not included.', 3, 4, 3, 'https://nimax-img.de/Produktbilder/big/6673_1/Zoffoli-Globe-Bar-Giunone-Laguna-40cm.jpg', '- Total dimensions: 50 × 50 × h 93 cm\r\n\r\n- Sphere diameter: 40 cm, the inner compartment can accommodate up to 9 glasses and 2 or 3 bottles. Additional bottles can be stored on the lower base.\r\n\r\n- 16th century map\r\n\r\n- Colour: Laguna\r\n\r\n- Structure: 3 legs made of beech wood, northern meridian, internal rotating bottle rack, wheels.'),
('Giasone', 4095, 'Trolley globe with drink cabinet and tray\r\n\r\nEntertain your friends with this convenient bar globe which has been designed with hospitality and social life concept in mind! The upper serving tray in addition to the spacious drinks cabinet inside the globe itself, it will provide an excellent space to store bar accessories, decanters, glassware and your favourite bottles of wine and liquor. With its solid base, decorated by hand-finished screen-printings, this globe is a fine addition to any room. The globe sphere, whose map is a faithful reproduction of a 16th Century cartography, fully rotates around its meridian either when it is open or closed.\r\n\r\n- Designed to give a touch of elegance to your living room\r\n\r\n- Ideal to accompany an aperitif or an after dinner with friends or work colleagues\r\n\r\n- Perfect for decorating rooms in a classic style but does not exclude more modern locations\r\n\r\n- Suitable for those with large spaces (for greater enhancement of the product we suggest placing it in an environment of at least 90 x 70cm)\r\n\r\nBar accessories are not included.', 3, 4, 7, 'https://www.zoffoli.com/350-large_default/90.jpg', '- Dimensions: 72 × 53 × h 93 cm\r\n\r\n- Sphere diameter: 40 cm, the inner compartment can accommodate up to 9 glasses and 2/3 bottles. Additional bottles can be stored in the lower compartment and in the side tray.\r\n\r\n- 16th century map\r\n\r\n- Color: classic'),
('Vivalto', 4095, 'Vintage trolley bar globe on antiqued finish stand and classic ivory map. With its wonderful illustrations of sea monsters, mermaids and mythological figures, Vivalto globe can carry 2 or 3 bottles and approximately 9 glasses. The upper serving tray will provide an excellent space to store bar accessories, decanters, glassware and your favorite bottles of wine and liquor while additional bottles can be placed on the unique lower base shelf.\r\n\r\nIn this vintage styled map, imagination comes to life… A fascinating journey begins, one that combines the charm for maps, mythological illustrations and ancient symbolism. The planispheres realised with our Vintage Map will accompany you in this wonderful journey to the discovery of unexplored territories, with ancient sea routes, wind roses, sea monsters and mermaids. Reality and fantasy come together to create an horizon full of suggestions. A journey between space and time reserved for modern Argonauts thirsting for adventures.\r\n\r\n- Designed to give a touch of elegance to your living room\r\n\r\n- Ideal to accompany an aperitif or an after dinner with friends or work colleagues\r\n\r\nBar accessories not included.', 3, 4, 10, 'https://www.bronze-sculpture-art.com/wp-content/uploads/sites/2/2020/09/podlogowy-elegancki-bar-globe-z-taca.jpg', '- Dimensions: 80 × 50 × h 95 cm\r\n\r\n- Sphere diameter: 42 cm, the inner compartment can accommodate up to 9 glasses and 2/3 bottles. Additional bottles can be stored in the lower compartment and in the side tray.\r\n\r\n- Map: vintage\r\n\r\n- Colour: Ivory'),
('Minerva Blue Ocean', 3000, 'Elegant bar globe with wheels “Minerva Blue Ocean”\r\n\r\nIf you are looking for an original and quality piece of furniture, Minerva is the ideal choice. This bar globe is perfect for storing your favorite liqueurs to serve to your guests on special occasions. Wherever you choose to position it will certainly not go unnoticed!\r\n\r\nElegant floor-standing bar globe, Minerva has an inner compartment that can hold up to 9 glasses and 2 or 3 bottles. Additional bottles can be stored on the lower wooden base, beautifully decorated with screen-printing natural water-based colors. The map is an accurate reproduction of a 16th Century cartography. You can easily move it thanks to its casters.\r\n\r\n- Minerva is ideal for giving a touch of elegance and originality to your living room\r\n\r\n- Perfect to accompany an aperitif or after dinner with friends or work colleagues\r\n\r\n- It decorates classic style environments but does not exclude modern locations either\r\n\r\n- Suitable for those with limited spaces (for greater enhancement of the product we suggest placing it in an area of ​​at least 70 x 70 cm)\r\n\r\n- The &quot;Minerva&quot; globe is also perfect as a gift idea to amaze!\r\n\r\nBar accessories not included.', 3, 4, 2, 'https://www.bronze-sculpture-art.com/wp-content/uploads/sites/2/2020/09/drewniany-barek-globus-zoffoli-.jpg', '- Total dimensions: 50 × 50 × h 93 cm\r\n\r\n- Sphere diameter: 40 cm, the inner compartment can accommodate up to 9 glasses with a maximum diameter of 8 cm and 2/3 bottles. Additional bottles can be stored on the lower base.\r\n\r\n- 16th century map\r\n\r\n- Color: blue ocean\r\n\r\n- Structure: 4 legs in beech wood, north and south meridian, internal revolving bottle rack, wheels'),
('Hunter\'s Trophy Antler Wall Décor', 3400, 'This deer antler skull cap mount is a large piece of taxidermy home decor. Many other skull caps are small, but this one is large! This antler wall mount is a perfect size and truly high quality, attractive piece of art. This piece is sure to please. This antler mount has been crafted with high-quality resin. This plaque is perfect for a man cave, bar, or above a bedroom headboard or fireplace.', 3, 5, 3, 'https://secure.img1-fg.wfcdn.com/im/10039311/resize-h800-w800%5Ecompr-r85/1381/138165651/Hunter%27s+Trophy+Antler+Wall+D%C3%A9cor.jpg', 'Color: Gray\r\nWall Mounting Hardware Included: Yes\r\nOutdoor Use: No\r\nResidential Use\r\nOrientation: Vertical Only\r\nCountry of Origin: Made in USA of Imported Materials'),
('Taxidermy Moose Skull Wall Décor', 2895, 'This Taxidermy Moose Skull Wall Décor is truly unique. This piece brings rustic animal decor to the modern age and will be sure to spark conversation in your home. Hang this moose skull in your living space, bedroom, entryway, or office and show off your decor style!', 3, 5, 1, 'https://secure.img1-fg.wfcdn.com/im/41565293/resize-h800-w800%5Ecompr-r85/1382/138246453/Faux+Taxidermy+Moose+Skull+Wall+D%C3%A9cor.jpg', 'Size: 20.5\'\' H x 23\'\' W x 7\'\' D\r\nWeight: 5 lb.\r\nOutdoor Use: No\r\nOrientation: Vertical Only\r\nCountry of Origin: United States'),
('Whiskey Barrel Bar', 7995, 'Whiskey Barrel Bars are for those who want to add that IT factor in your bar area.  Have you been told to get your liquor out of your kitchen?  Not enough room on your bar shelves?  Add this to your bar area and all of your friends will be jealous!  The whiskey barrel bar can include a door and even lighting. This item can be cleared by either a poly or water based clear coat.', 3, 5, 12, 'https://www.baukolsbarrels.com/wp-content/uploads/2020/11/Whiskey-Barrel-Bar-5-600x636.jpeg', '***Whiskey Barrels vary in color and age. Because of this, we can not guarantee the color for each barrel.'),
('Skull &amp; Antler Art Print', 800, 'Skull &amp; Antler Study I by Ethan Harper, Art Print\r\nART PRINTS are produced on professional-grade paper using high-end equipment to yield a gallery-quality product with stunning vibrancy.', 3, 6, 20, 'https://images.barewalls.com/bwcomp/art-print-poster/bw1232660/skull-antler-study-i.jpg?units=cm&amp;pw=60.96&amp;ph=81.28', 'Open Edition Giclee - Matte - Art Print'),
('American Trophy III Art Print', 800, 'American Trophy III by John Butler, Art Print\r\nART PRINTS are produced on professional-grade paper using high-end equipment to yield a gallery-quality product with stunning vibrancy.', 3, 6, 20, 'https://images.barewalls.com/bwcomp/art-print-poster/bw1191909/american-trophy-iii.jpg?units=cm&amp;pw=55.88&amp;ph=76.2', 'Open Edition Giclee - Matte - Art Print'),
('American Trophy II Art Print', 800, 'American Trophy II by John Butler, Art Print\r\nART PRINTS are produced on professional-grade paper using high-end equipment to yield a gallery-quality product with stunning vibrancy.', 3, 6, 20, 'https://images.barewalls.com/bwcomp/art-print-poster/bw1191777/american-trophy-ii.jpg?units=cm&amp;pw=55.88&amp;ph=76.2', 'Open Edition Giclee - Matte - Art Print'),
('Beer - The Reason, Art Print', 300, 'ART PRINTS are produced on professional-grade paper using high-end equipment to yield a gallery-quality product with stunning vibrancy.', 3, 6, 40, 'https://cdn.shopify.com/s/files/1/0756/6205/products/The.Reason.Dark_2048x2048.jpg?v=1605978357', ''),
('Beer - The Reason, Metal Novelty', 495, 'Beer Sign The Reason I Wake Up Every Afternoon Metal Novelty Sign\r\n\r\nThis sign features rolled edges, embossed features and weatherproof finish for indoor or outdoor use.', 3, 6, 50, 'https://images-na.ssl-images-amazon.com/images/I/71WU%2BurAJgL._AC_SY679_.jpg', 'Measures 12&quot; x 16-3/4&quot; and has pre-drilled holes on each corner for hanging.');
